name: Build and Deply Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_URL: ${{env.DATABASE_UR}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{env.ACCESS_TOKEN_EXPIRE_MINUTES}}
      ALGORITHM: ${{env.ALGORITHM}}    
      SECRET_KEY: ${{env.SECRET_KEY}}
      POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{env.POSTGRES_DB}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v6
      - name: say hy
        run: echo "hello modou"
      - name: install python version 3.14.0
        uses: actions/setup-python@v6 
        with:
          python-version: "3.14"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
